# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,mapping:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Taxonomic group
taxonomic_group: beetles
# Name of species being analyzed
species_name: Stenus fulvicornis
# Path to reference genome file in FASTA format
reference_genome_path: 
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps
# # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
output_directory_path: /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/
# AdapterRemoval settings.
adapterremoval_settings:
  min_quality: 25
  min_length: 20
  adaptersequence1: AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
  adaptersequence2: AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG
# Samtools filter settings.
filter_settings:
  flags_excluded: 3844
  flags_required: 
  min_mq: 20
# List of path to sample folders containing resequencing data.
sample_lists:
  -
    group_name: Grassland
    sample_folder_list:
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Stenus_fulvicornis/SteFul_aeRoe
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Stenus_fulvicornis/SteFul_BIJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Stenus_fulvicornis/SteFul_DoeJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Stenus_fulvicornis/SteFul_DSJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Stenus_fulvicornis/SteFul_GSJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Stenus_fulvicornis/SteFul_JEJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Stenus_fulvicornis/SteFul_LEJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Stenus_fulvicornis/SteFul_LVJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Stenus_fulvicornis/SteFul_MSJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Stenus_fulvicornis/SteFul_SKJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Stenus_fulvicornis/SteFul_SKS
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Stenus_fulvicornis/SteFul_SUJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Stenus_fulvicornis/SteFul_TRJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Stenus_fulvicornis/SteFul_ULJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Stenus_fulvicornis/SteFul_aaRJ
  -
    group_name: Conservation_agriculture
    sample_folder_list:
  -
    group_name: Conventional_agriculture
    sample_folder_list:
  -
    group_name: 
    sample_folder_list: