# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,museomics,mapping:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed
species_name: Lycaena hippothoe
# Path to reference genome file in FASTA format
reference_genome_path: /faststorage/project/EcoGenetics/BACKUP/museomics/reference_genomes/Lycaena_hippothoe/GCA_964264095.1.fasta
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/museomics/steps
# # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
output_directory_path: /faststorage/project/EcoGenetics/general_workflow_outputs/museomics
# AdapterRemoval settings.
adapterremoval_settings:
  min_quality: 25
  min_length: 20
  adaptersequence1: AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
  adaptersequence2: AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG
# Samtools filter settings.
filter_settings:
  flags_excluded: 3844
  flags_required: 
  min_mq: 20
# List of path to sample folders containing resequencing data.
# Data type: contemporary | historic | paired-end | single-end ...
sample_lists:
  -
    time_period: 2022
    data_type: contemporary, paired-end
    populations:
      -
        population_name: Finland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/LH23_1
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/LH24_1
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/LH24_2
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/LH24_3
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/LH24_4
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/LH24_5
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/LH24_7
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/LH24_9
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/LH24_10
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/LH24_11
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/LH24_12
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/LH24_13
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/LH24_14
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/LH24_15
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/LH24_16
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/LH24_17
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/LH24_18
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/LH24_19
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/LH24_20
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/LH24_21
  -
    time_period: 1985
    data_type: historic, single-end
    populations:
      -
        population_name: Finland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M161
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M162
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M163
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M164
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M165
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M166
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M167
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M168
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M169
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M170
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M171
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M172
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M173
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M174
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M175
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M176
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M177
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M178
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M179
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M180
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M181
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M182
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M183
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M184
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M185
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M186
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M187
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M188
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M189
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M190
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M191
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M192
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M193
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M194
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M195
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M196
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M197
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M198
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M199
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M200
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M201
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M202
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M203
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M204
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M205
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M206
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M207
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M208
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M209
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M210
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M211
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M212
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M213
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M214
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M215
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_hippothoe/Lhi_M216
