# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,vcf:workflowconfiguration
# (str). The name of the relevant project account.
account: EcoGenetics
# (str). Taxonomic group. Can be left empty.
taxonomicGroup: collembola
# (str). Name of species being analyzed.
speciesName: Lepidocyrtus lignorum
# (str). Path to reference genome.
referenceGenomePath: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Lepidocyrtus_lignorum/EG_LepLig_16022023_genomic_nomask_noann.fna
# (str). BED file indicating intergenic regions of the reference genome.
intergenicBedFile: 
# (str). BED file indicating repetitive regions of the reference genome.
repeatsBedFile: 
# (str). Directory for intermediary files.
workingDirectoryPath: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps/
# (str). Directory for final output files. (If left empty, output file will be placed within 'working_directory_path').
outputDirectoryPath: /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/
# (int). Partition size of genome in base pairs. If left empty defaults to '500000'.
partitionSize: 100000
# Variant caller, Freebayes settings.
freebayesSettings:
  # (0 | 1 | 2). Mode for creating VCF file.
  # 1 = Separate VCF files for each sample/BAM file. 2 = One VCF containing data for all samples/BAM files. 0 = Both.
  mode: 1
  # (int). sample_ploidy = ploidy * n_individials. If left empty defaults to '100'.
  samplePloidy: 100
  # (int). Number of variants to consider and report when multiple are available. If left empty defaults to '3'
  bestNAlleles: 3 
  # (0 | float). Lower threshold fraction for variant to be considered. If left empty defaults to '0'.
  minAlternateFraction: 0
  # (int). Lower threshold count for variant to be considered. If left empty defaults to '2'.
  minAlternateCount: 2
  # (int). Amount of memory, in GB, to reserve per VCF partition. If left empty defaults to '80'.
  memory: 35 
  # (str). Amount of time to reserve per VCF partition in format: 'tt:mm:ss'. If left empty defaults to '48:00:00'.
  time: '24:00:00'
# Filtering depths, limits included.
filtering:
  # (int). Minimum required depth for ingroups, inclusive. If left empty deafults to '200'.
  ingroupMinimumDepth: 200
  # (int). Absolute minimum required depth for outgroups, inclusive. If left empty defaults to '5'.
  outgroupMinimumDepth: 
# Batch settings. Can be used to reduced the number of jobs sent to the queue at one time.
# Only partial VCF files will be created when batching. To complete the full workflow one must do a no-batch run.
batchSettings:
  # (int). The number of batches to create. 0 = don't batch jobs. If left empty defaults to '0'
  numberOfBatches: 
  # (int). Which of the created batches to run. Must be >=1 AND <=number_of_batches. Can be left empty if number_of_batches is '0'.
  currentBatchNumber: 
# (list). Sample setup. List of dictionaries listing the configuration for each sample.
sampleList:
  - 
    # ('i' | 'o'). Whether the sample group is to be considered ingroup (i) or outgroup (o).
    groupStatus: i
    # (str). Name of sample group.
    groupName: grassland
    # (list). List of paths to BAM files.
    bamFileList:
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Lepidocyrtus_lignorum/grassland/LepLig_BRS-C269/LepLig_BRS-C269.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Lepidocyrtus_lignorum/grassland/LepLig_FHJ-C92/LepLig_FHJ-C92.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Lepidocyrtus_lignorum/grassland/LepLig_FUR-C231/LepLig_FUR-C231.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Lepidocyrtus_lignorum/grassland/LepLig_FaaJ-C8/LepLig_FaaJ-C8.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Lepidocyrtus_lignorum/grassland/LepLig_GoeJ-C242/LepLig_GoeJ-C242.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Lepidocyrtus_lignorum/grassland/LepLig_GSJ-C273/LepLig_GSJ-C273.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Lepidocyrtus_lignorum/grassland/LepLig_HHJ-C215/LepLig_HHJ-C215.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Lepidocyrtus_lignorum/grassland/LepLig_JEJ-C18/LepLig_JEJ-C18.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Lepidocyrtus_lignorum/grassland/LepLig_KOS-C181/LepLig_KOS-C181.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Lepidocyrtus_lignorum/grassland/LepLig_LEJ-C243/LepLig_LEJ-C243.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Lepidocyrtus_lignorum/grassland/LepLig_LVJ-C78/LepLig_LVJ-C78.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Lepidocyrtus_lignorum/grassland/LepLig_MYS-C39/LepLig_MYS-C39.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Lepidocyrtus_lignorum/grassland/LepLig_RES-C286/LepLig_RES-C286.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Lepidocyrtus_lignorum/grassland/LepLig_SHJ-C9/LepLig_SHJ-C9.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Lepidocyrtus_lignorum/grassland/LepLig_SKS-C106/LepLig_SKS-C106.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Lepidocyrtus_lignorum/grassland/LepLig_SSJ-C258/LepLig_SSJ-C258.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Lepidocyrtus_lignorum/grassland/LepLig_VAJ-C10/LepLig_VAJ-C10.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Lepidocyrtus_lignorum/grassland/LepLig_aaRJ-C207/LepLig_aaRJ-C207.filtered.bam
  -
    # ('i' | 'o'). Whether the sample group is to be considered ingroup (i) or outgroup (o).
    groupStatus: i
    # (str). Name of sample group.
    groupName: Conservation_agriculture
    # (list). List of paths to BAM files.
    bamFileList:
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Lepidocyrtus_lignorum/conservation_agriculture/LepLig_CA-FS6J-C90/LepLig_CA-FS6J-C90.filtered.bam
  -
    # ('i' | 'o'). Whether the sample group is to be considered ingroup (i) or outgroup (o).
    groupStatus: i
    # (str). Name of sample group.
    groupName: Conventional_agriculture
    # (list). List of paths to BAM files.
    bamFileList:
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Lepidocyrtus_lignorum/conventional_agriculture/LepLig_K-JES-C324/LepLig_K-JES-C324.filtered.bam
