# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,mapping:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Taxonomic group
taxonomic_group: Collembola
# Name of species being analyzed
species_name: Isotoma viridis
# Path to reference genome file in FASTA format
reference_genome_path: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Isotoma_viridis/EG_IsoVir_23082024_genomic.fna
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps
# # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
output_directory_path: /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/
# AdapterRemoval settings.
adapterremoval_settings:
  min_quality: 25
  min_length: 20
  adaptersequence1: AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
  adaptersequence2: AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG
# Samtools filter settings.
filter_settings:
  flags_excluded: 3844
  flags_required: 
  min_mq: 20
# List of path to sample folders containing resequencing data.
sample_lists:
  -
    group_name: Grassland
    sample_folder_list:
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_aeRoe-C310
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_BJJ-C98
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_BIJ-C211
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_DoeJ-C422
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_DSJ-C236
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_FHJ-C362
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_FUR-C232
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_FaaJ-C417
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_GoeJ-C135
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_GSJ-C275
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_HaeJ-C283
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_HYF-C156
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_JEJ-C290
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_JHJ-C224
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_JoeJ-C251
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_JYS-C175
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_KLJ-C204
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_KoeJ-C213
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_KOS-C179
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_KRS-C186
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_LEJ-C67
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_MSJ-C319
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_MSS-C296
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_MYS-C153
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_NOJ-C262
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_NYS-F-C118
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_RES-C168
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_RMJ-C306
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_RYJ-C17
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_SBJ-C73
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_SHJ-C321
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_SKS-C56
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_SSJ-C260
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_STF-C445
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_STJ-C444
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_TOJ-C72
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_TRJ-C346
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_aaRJ-C229
  -
    group_name: Conservation_agriculture
    sample_folder_list:
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_CA-BMJ-C121
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_CA-FSJ-C221
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_CA-FSJ-C91
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_CA-HVJ-C302
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_CA-HYS-C379
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_CA-JES-C303
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_CA-KNJ-C209
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_CA-LES-C351
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_CA-MoeJ-C354
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_CA-YDJ-C120
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_CA_DAS-C431
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_CA_FLJ-C394
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_CA_RoeF-C338
  -
    group_name: Conventional_agriculture
    sample_folder_list:
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_K-DAS-C330
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_K-FLJ-C332
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_K-FSJ-C210
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_K-HVJ-C246
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_K-HYS-C337
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_K-JES-C325
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_K-KNJ-C217
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_K-LES-C385
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_K-MoeJ-C365
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_K-ToeJ-C301
  -
    group_name: Outgroup_Isotomurus_maculatus
    sample_folder_list:
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotomurus_maculatus/IsoMac_CA-BMJ-C403
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotomurus_maculatus/IsoMac_CA-LES-C387
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotomurus_maculatus/IsoMac_K-FLJ-C370
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotomurus_maculatus/IsoMac_K-HVJ-C376