# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,filter,aa,snpeff:workflowconfiguration
# (str). The name of the relevant project account.
account: EcoGenetics
# (str). Name of species being analyzed
speciesName: Maniola jurtina
# (str). Taxonomic group. Can be left empty.
taxonomicGroup: butterflies
# (str). Directory for intermediary files.
workingDirectoryPath: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/museomics/steps
# (str). Directory for final output files.
outputDirectoryPath: /faststorage/project/EcoGenetics/general_workflow_outputs/museomics
# (str). Path to reference genome file.
referenceGenome: /faststorage/project/EcoGenetics/BACKUP/museomics/reference_genomes/Maniola_jurtina/GCF_905333055.1_ilManJurt1.1_genomic.fna
# (str). Path to reference genome annotation file in GTF format. Can be left empty. If left empty VCF file will not be SnpEff or AA annotated.
gtfAnnotation: /faststorage/project/EcoGenetics/BACKUP/museomics/reference_genomes/Maniola_jurtina/annotation/GCF_905333055.1_ilManJurt1.1_genomic.gtf
# (dict). Settings for outgroup data. Can be left empty. If left empty VCF file will not be AA annotated.
outgroupSettings:
  # (str). Path to outgroup VCF file. This file should NOT be filtered.
  vcfFile: 
  # (str). Path to BED file containing intervals for which the outgroup has coverage ranging within threshold values. 
  withinThresholdBedFile: 
# (list). Setup for VCF files to be filtered and annotated.
vcfGroupList:
  -
    # (str). Name of sample group.
    groupName: Grassland
    # (str). Path to VCF file.
    vcfFile: /faststorage/project/EcoGenetics/general_workflow_outputs/museomics/vcf/pooled/vcf/butterflies/Maniola_jurtina/grassland/ManJur.grassland.ingroup.allQuality.freebayes.vcf.gz
    # (int). Minimum coverage value for filtering.
    minimumCoverage: 200
    # (int). Maximum coverage value for filtering.
    maximumCoverage: 464
    # (str). Path to BED file containing intervals for which the sample group has coverage ranging within threshold values. 
    withinThresholdBedFile: /faststorage/project/EcoGenetics/general_workflow_outputs/museomics/vcf/pooled/vcf/butterflies/Maniola_jurtina/depth/ManJur.grassland.ingroup.allQuality.depththreshold.bed
