# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,vcf:workflowconfiguration
# (str). The name of the relevant project account.
account: EcoGenetics
# (str). Taxonomic group. Can be left empty.
taxonomic_group: Collembola
# (str). Name of species being analyzed.
species_name: Entomobrya nicoleti
# (str). Path to reference genome.
reference_genome_path: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Entomobrya_nicoleti/EG_EntNic_05092024_genomic.fna
# (str). BED file indicating intergenic regions of the reference genome.
intergenic_bed_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Entomobrya_nicoleti/annotation/EG_EntNic_05092024_genomic.intergenic.bed
# (str). BED file indicating repetitive regions of the reference genome. If left empty workflow will try to extract repetitive regions from reference genome.
repeats_bed_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Entomobrya_nicoleti/annotation/EG_EntNic_05092024_genomic.repeats.bed
# (str). Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps
# (str). Directory for final output files. (If left empty, output file will be placed within 'working_directory_path').
output_directory_path: /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics
# (int). Partition size of genome in base pairs. If left empty defaults to '500000'.
partition_size: 100000
# Variant caller, Freebayes settings.
freebayes_settings:
  # (int). sample_ploidy = ploidy * n_individials. If left empty defaults to '100'.
  sample_ploidy: 100
  # (int). Number of variants to consider and report when multiple are available. If left empty defaults to '3'.
  best_n_alleles: 3
  # (0 | float). Lower threshold fraction for variant to be considered. If left empty defaults to '0'.
  min_alternate_fraction: 0
  # (int). Lower threshold count for variant to be considered. If left empty defaults to '2'.
  min_alternate_count: 2
  # (int). Amount of memory, in GB, to reserve per VCF partition. If left empty defaults to '80'.
  memory: 35
  # (str). Amount of time to reserve per VCF partition in format: 'tt:mm:ss'. If left empty defaults to '48:00:00'.
  time: 24:00:00
# Filtering settings.
filtering:
  # (int). Minimum required depth, inclusive.
  minimum_depth: 200
# (int). Mode for creating VCF file (1 | 2 | 3 | 4).
# 1 = Separate VCF files for each sample/BAM file. 2 = One VCF file per sample group. 3 = One VCF containing data for all samples/BAM files. 4 = All.
mode: 1
# Batch settings. Can be used to reduced the number of jobs sent to the queue at one time.
# Only partial VCF files will be created when batching. To complete the full workflow one must do a no-batch run.
batch_settings:
  # (int). The number of batches to create. 0 = don't batch jobs. If left empty defaults to '0'
  number_of_batches: 8
  # (int). Which of the created batches to run. Must be >=1 AND <=number_of_batches. Can be left empty if number_of_batches is '0'.
  current_batch_number: 1
# (list). Sample setup. List of dictionaries listing the configuration for each sample.
sample_list:
  - 
    # (str). Name of sample group.
    group_name: Grassland
    # (list). List of paths to BAM files.
    bam_file_list:
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_aeRoe-C36/EntNic_aeRoe-C36.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_BIJ-C30/EntNic_BIJ-C30.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_BJJ-C34/EntNic_BJJ-C34.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_BRS-C268/EntNic_BRS-C268.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_DoeJ-C27/EntNic_DoeJ-C27.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_DSJ-C190/EntNic_DSJ-C190.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_FHJ-C38/EntNic_FHJ-C38.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_FUR-C230/EntNic_FUR-C230.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_GEJ-C42/EntNic_GEJ-C42.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_GoeJ-C19/EntNic_GoeJ-C19.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_GSJ-C274/EntNic_GSJ-C274.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_GUS-C41/EntNic_GUS-C41.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_HAS-C59/EntNic_HAS-C59.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_JHJ-C220/EntNic_JHJ-C220.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_JoeJ-C252/EntNic_JoeJ-C252.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_KLJ-C127/EntNic_KLJ-C127.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_KOS-C293/EntNic_KOS-C293.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_KRS-C23/EntNic_KRS-C23.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_LEJ-C64/EntNic_LEJ-C64.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_MMS-C295/EntNic_MMS-C295.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_MSJ-C2/EntNic_MSJ-C2.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_NOJ-C37/EntNic_NOJ-C37.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_ORoe-C299/EntNic_ORoe-C299.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_RDJ-C344/EntNic_RDJ-C344.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_RYJ-C139/EntNic_RYJ-C139.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_SBJ-C52/EntNic_SBJ-C52.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_SHJ-C48/EntNic_SHJ-C48.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_SKJ-C16/EntNic_SKJ-C16.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_SKJ-C216/EntNic_SKJ-C216.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_SKS-C55/EntNic_SKS-C55.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_SSJ-C259/EntNic_SSJ-C259.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_STF-C266/EntNic_STF-C266.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_STF-C266/EntNic_STF-C266.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_SUJ-C130/EntNic_SUJ-C130.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_ULJ-C60/EntNic_ULJ-C60.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_ULJ-C122/EntNic_ULJ-C122.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_UTJ-C22/EntNic_UTJ-C22.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/grassland/EntNic_aaRJ-C225/EntNic_aaRJ-C225.filtered.bam
  - 
    # (str). Name of sample group.
    group_name: Conventional_agriculture
    # (list). List of paths to BAM files.
    bam_file_list:
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/conventional_agriculture/EntNic_K-JES-C323/EntNic_K-JES-C323.filtered.bam
  - 
    # (str). Name of sample group.
    group_name: Conservation_agriculture
    # (list). List of paths to BAM files.
    bam_file_list:
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/conservation_agriculture/EntNic_CA-MOJ-C55/EntNic_CA-MOJ-C55.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/conservation_agriculture/EntNic_CA-ST-6J-C84/EntNic_CA-ST-6J-C84.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/conservation_agriculture/EntNic_CA-ToeJ-C85/EntNic_CA-ToeJ-C85.filtered.bam
  - 
    # (str). Name of sample group.
    group_name: Outgroup_Entomobrya_nivalis
    # (list). List of paths to BAM files.
    bam_file_list:
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/outgroup_entomobrya_nivalis/EntNiv_MSJ-C93/EntNiv_MSJ-C93.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/outgroup_entomobrya_nivalis/EntNiv_RYJ-ENNI/EntNiv_RYJ-ENNI.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/outgroup_entomobrya_nivalis/EntNiv_SBJ-C104/EntNiv_SBJ-C104.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Entomobrya_nicoleti/outgroup_entomobrya_nivalis/EntNiv_ULJ-C124/EntNiv_ULJ-C124.filtered.bam
