# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,vcf:workflowconfiguration
# (str). The name of the relevant project account.
account: EcoGenetics
# (str). Taxonomic group. Can be left empty.
taxonomic_group: Collembola
# (str). Name of species being analyzed.
species_name: Isotoma viridis
# (str). Path to reference genome.
reference_genome_path: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Isotoma_viridis/EG_IsoVir_23082024_genomic.fna
# (str). BED file indicating intergenic regions of the reference genome.
intergenic_bed_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Isotoma_viridis/annotation/EG_IsoVir_23082024_genomic.intergenic.bed
# (str). BED file indicating repetitive regions of the reference genome. If left empty workflow will try to extract repetitive regions from reference genome.
repeats_bed_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Isotoma_viridis/annotation/EG_IsoVir_23082024_genomic.repeats.bed
# (str). Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps
# (str). Directory for final output files. (If left empty, output file will be placed within 'working_directory_path').
output_directory_path: /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics
# (int). Partition size of genome in base pairs. If left empty defaults to '500000'.
partition_size: 100000
# Variant caller, Freebayes settings.
freebayes_settings:
  # (int). sample_ploidy = ploidy * n_individials. If left empty defaults to '100'.
  sample_ploidy: 100
  # (int). Number of variants to consider and report when multiple are available. If left empty defaults to '3'
  best_n_alleles: 3
  # (0 | float). Lower threshold fraction for variant to be considered. If left empty defaults to '0'.
  min_alternate_fraction: 0
  # (int). Lower threshold count for variant to be considered. If left empty defaults to '2'.
  min_alternate_count: 2
  # (int). Amount of memory, in GB, to reserve per VCF partition. If left empty defaults to '80'.
  memory: 35
  # (str). Amount of time to reserve per VCF partition in format: 'tt:mm:ss'. If left empty defaults to '48:00:00'.
  time: '12:00:00'
# Filtering settings.
filtering:
  # (int). Minimum required depth, inclusive.
  minimum_depth: 200
# (int). Mode for creating VCF file (1 | 2 | 3 | 4).
# 1 = Separate VCF files for each sample/BAM file. 2 = One VCF file per sample group. 3 = One VCF containing data for all samples/BAM files. 4 = All.
mode: 1
# Batch settings. Can be used to reduced the number of jobs sent to the queue at one time.
# Only partial VCF files will be created when batching. To complete the full workflow one must do a no-batch run.
batch_settings:
  # (int). The number of batches to create. 0 = don't batch jobs. If left empty defaults to '0'
  number_of_batches: 4
  # (int). Which of the created batches to run. Must be >=1 AND <=number_of_batches. Can be left empty if number_of_batches is '0'.
  current_batch_number: 2
# (list). Sample setup. List of dictionaries listing the configuration for each sample.
sample_list:
  - 
    # (str). Name of sample group.
    group_name: Grassland
    # (list). List of paths to BAM files.
    bam_file_list:
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_aeRoe-C310/IsoVir_aeRoe-C310.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_BJJ-C98/IsoVir_BJJ-C98.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_DSJ-C236/IsoVir_DSJ-C236.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_FUR-C232/IsoVir_FUR-C232.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_GoeJ-C135/IsoVir_GoeJ-C135.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_GSJ-C275/IsoVir_GSJ-C275.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_HaeJ-C283/IsoVir_HaeJ-C283.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_HYF-C156/IsoVir_HYF-C156.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_JEJ-C290/IsoVir_JEJ-C290.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_JHJ-C224/IsoVir_JHJ-C224.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_JoeJ-C251/IsoVir_JoeJ-C251.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_JYS-C175/IsoVir_JYS-C175.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_KoeJ-C213/IsoVir_KoeJ-C213.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_KOS-C179/IsoVir_KOS-C179.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_KRS-C186/IsoVir_KRS-C186.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_LEJ-C67/IsoVir_LEJ-C67.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_MSJ-C319/IsoVir_MSJ-C319.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_MSS-C296/IsoVir_MSS-C296.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_MYS-C153/IsoVir_MYS-C153.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_RES-C168/IsoVir_RES-C168.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_RMJ-C306/IsoVir_RMJ-C306.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_RYJ-C17/IsoVir_RYJ-C17.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_SBJ-C73/IsoVir_SBJ-C73.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_SHJ-C321/IsoVir_SHJ-C321.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_SKS-C56/IsoVir_SKS-C56.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/grassland/IsoVir_TOJ-C72/IsoVir_TOJ-C72.filtered.bam
  - 
    # (str). Name of sample group.
    group_name: Conventional_agriculture
    # (list). List of paths to BAM files.
    bam_file_list:
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/conventional_agriculture/IsoVir_K-DAS-C330/IsoVir_K-DAS-C330.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/conventional_agriculture/IsoVir_K-FLJ-C332/IsoVir_K-FLJ-C332.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/conventional_agriculture/IsoVir_K-FSJ-C210/IsoVir_K-FSJ-C210.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/conventional_agriculture/IsoVir_K-HVJ-C246/IsoVir_K-HVJ-C246.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/conventional_agriculture/IsoVir_K-HYS-C337/IsoVir_K-HYS-C337.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/conventional_agriculture/IsoVir_K-JES-C325/IsoVir_K-JES-C325.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/conventional_agriculture/IsoVir_K-KNJ-C217/IsoVir_K-KNJ-C217.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/conventional_agriculture/IsoVir_K-LES-C385/IsoVir_K-LES-C385.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/conventional_agriculture/IsoVir_K-MoeJ-C365/IsoVir_K-MoeJ-C365.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/conventional_agriculture/IsoVir_K-ToeJ-C301/IsoVir_K-ToeJ-C301.filtered.bam
  - 
    # (str). Name of sample group.
    group_name: Conservation_agriculture
    # (list). List of paths to BAM files.
    bam_file_list:
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/conservation_agriculture/IsoVir_CA-BMJ-C121/IsoVir_CA-BMJ-C121.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/conservation_agriculture/IsoVir_CA-FSJ-C221/IsoVir_CA-FSJ-C221.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/conservation_agriculture/IsoVir_CA-FSJ-C91/IsoVir_CA-FSJ-C91.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/conservation_agriculture/IsoVir_CA-HVJ-C302/IsoVir_CA-HVJ-C302.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/conservation_agriculture/IsoVir_CA-HYS-C379/IsoVir_CA-HYS-C379.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/conservation_agriculture/IsoVir_CA-JES-C303/IsoVir_CA-JES-C303.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/conservation_agriculture/IsoVir_CA-KNJ-C209/IsoVir_CA-KNJ-C209.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/conservation_agriculture/IsoVir_CA-LES-C351/IsoVir_CA-LES-C351.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/conservation_agriculture/IsoVir_CA-MoeJ-C354/IsoVir_CA-MoeJ-C354.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/conservation_agriculture/IsoVir_CA-YDJ-C120/IsoVir_CA-YDJ-C120.filtered.bam
  - 
    # (str). Name of sample group.
    group_name: Outgroup_Isotomurus_maculatus
    # (list). List of paths to BAM files.
    bam_file_list:
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/outgroup_isotomurus_maculatus/IsoMac_CA-BMJ-C403/IsoMac_CA-BMJ-C403.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/outgroup_isotomurus_maculatus/IsoMac_CA-LES-C387/IsoMac_CA-LES-C387.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Isotoma_viridis/outgroup_isotomurus_maculatus/IsoMac_K-FLJ-C370/IsoMac_K-FLJ-C370.filtered.bam