# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,filter,aa,snpeff:workflowconfiguration
# (str). The name of the relevant project account.
account: EcoGenetics
# (str). Name of species being analyzed
speciesName: Lycaena virgaureae
# (str). Taxonomic group. Can be left empty.
taxonomicGroup: butterflies
# (str). Directory for intermediary files.
workingDirectoryPath: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/museomics/steps
# (str). Directory for final output files.
outputDirectoryPath: /faststorage/project/EcoGenetics/general_workflow_outputs/museomics
# (str). Path to reference genome file.
referenceGenome: /faststorage/project/EcoGenetics/BACKUP/museomics/reference_genomes/Lycaena_virgaureae/EG_LycVir_01052024_genomic_haplotype1.fna
# (str). Path to reference genome annotation file in GTF format. Can be left empty. If left empty VCF file will not be SnpEff or AA annotated.
gtfAnnotation: 
# (dict). Settings for outgroup data. Can be left empty. If left empty VCF file will not be AA annotated.
outgroupSettings:
  # (str). Path to outgroup VCF file. This file should NOT be filtered.
  vcfFile: 
  # (str). Path to BED file containing intervals for which the outgroup has coverage ranging within threshold values. 
  withinThresholdBedFile: 
# (list). Setup for VCF files to be filtered and annotated.
vcfGroupList:
  -
    # (str). Name of sample group.
    groupName: Grassland
    # (str). Path to VCF file.
    vcfFile: /faststorage/project/EcoGenetics/general_workflow_outputs/museomics/vcf/butterflies/Lycaena_virgaureae/grassland/LyVi_poolseq_2022/LyVi_poolseq_2022.freebayes_n3_p100_minaltfrc0_minaltcnt2_singlecall.vcf.gz
    # (int). Minimum coverage value for filtering.
    minimumCoverage: 200
    # (int). Maximum coverage value for filtering.
    maximumCoverage: 360
    # (str). Path to BED file containing intervals for which the sample group has coverage ranging within threshold values. 
    withinThresholdBedFile: /faststorage/project/EcoGenetics/general_workflow_outputs/museomics/vcf/butterflies/Lycaena_virgaureae/depth/LycVir.grassland.ingroup.allQuality.depththreshold.bed
