# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,mapping:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Taxonomic group
taxonomic_group: collembola
# Name of species being analyzed
species_name: Lepidocyrtus lignorum
# Path to reference genome file in FASTA format
reference_genome_path: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Lepidocyrtus_lignorum/EG_LepLig_16022023_genomic_nomask_noann.fna
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps
# # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
output_directory_path: /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics
# AdapterRemoval settings.
adapterremoval_settings:
  min_quality: 25
  min_length: 20
  adaptersequence1: AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
  adaptersequence2: AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG
# Samtools filter settings.
filter_settings:
  flags_excluded: 3844
  flags_required: 
  min_mq: 20
# List of path to sample folders containing resequencing data.
sample_lists:
  -
    group_name: Grassland
    sample_folder_list:
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_aaRJ-C207
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_BJJ-C97
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_BRS-C269
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_FaaJ-C8
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_FHJ-C92
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_FUR-C231
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_GoeJ-C242
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_GSJ-C273
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_HHJ-C215
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_JEJ-C18
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_JoeJ-C253
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_KRJ-C356
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_KOS-C181
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_LEJ-C243
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_LVJ-C78
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_RDJ-C245
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_SBJ-C449
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_MYS-C39
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_RES-C286
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_SHJ-C9
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_SKJ-C102
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_SKS-C106
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_SSJ-C258
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_VAJ-C10
  -
    group_name: Conservation_agriculture
    sample_folder_list:
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_CA-FS6J-C90
  -
    group_name: Conventional_agriculture
    sample_folder_list:
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Lepidocyrtus_lignorum/LepLig_K-JES-C324
  -
    group_name: Outgroup_Entomobrya_nicoleti
    sample_folder_list:
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Entomobrya_nicoleti/EntNic_aaRJ-C225
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Entomobrya_nicoleti/EntNic_GSJ-C274
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Entomobrya_nicoleti/EntNic_CA-ToeJ-C85
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Entomobrya_nicoleti/EntNic_K-JES-C323