# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,mapping:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Taxonomic group
taxonomic_group: Collembola
# Name of species being analyzed
species_name: Orchesella cincta
# Path to reference genome file in FASTA format
reference_genome_path: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Orchesella_cincta/GCA_001718145.1_ASM171814v1_genomic.fna
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps
# # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
output_directory_path: /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics
# AdapterRemoval settings.
adapterremoval_settings:
  min_quality: 25
  min_length: 20
  adaptersequence1: AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
  adaptersequence2: AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG
# Samtools filter settings.
filter_settings:
  flags_excluded: 3844
  flags_required: 
  min_mq: 20
# List of path to sample folders containing resequencing data.
sample_lists:
  -
    group_name: Grassland
    sample_folder_list:
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_cincta/OrcCin_aeRoe-C182
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_cincta/OrcCin_GoeJ-C14
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_cincta/OrcCin_KLJ-C204
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_cincta/OrcCin_MYS-C137
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_cincta/OrcCin_SBJ-C51
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_cincta/OrcCin_SSJ-C257
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_cincta/OrcCin_DSJ-C233
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_cincta/OrcCin_FaaJ-C6
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_cincta/OrcCin_JHJ-C222
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_cincta/OrcCin_KLJ-C49
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_cincta/OrcCin_KOS-C178
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_cincta/OrcCin_LEJ-C63
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_cincta/OrcCin_MSJ-C87
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_cincta/OrcCin_MSS-C198
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_cincta/OrcCin_NYS-F-C25-1
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_cincta/OrcCin_NYS-F-C25-2
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_cincta/OrcCin_ORoe-C31
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_cincta/OrcCin_RYJ
  -
    group_name: Conservation_agriculture
    sample_folder_list:
  -
    group_name: Conventional_agriculture
    sample_folder_list:
  -
    group_name: Outgroup_Orchesella_villosa
    sample_folder_list:
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_villosa/OrcVil_BRS-C95
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_villosa/OrcVil_CA-KNJ-C208
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_villosa/OrcVil_FaaJ-C5
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Orchesella_villosa/OrcVil_K-KNJ-C219
