# Tag identifying file association.
TAG: anneaa:EcoGenetics,population_genetics,DiversityEstimates:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Taxonomic group
taxonomic_group: pooled
# Name of species being analyzed
species_name: Gonepteryx rhamni
# Path to reference genome file in FASTA format
reference_genome_path: /home/anneaa/EcoGenetics/BACKUP/museomics/reference_genomes/Gonepteryx_rhamni/EG_GonRha_22032024_genomic.fna

# Directory for intermediary files.
working_directory_path: /home/anneaa/EcoGenetics/people/anneaa/derived_dat_scripts/neutral_diversity_pipeline/fst_pi_gwf_intermediate_steps
  #/faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps
# # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
  # this is where new fst/taxonomy or pi/taxonomy directories with outputs will be placed
output_directory_path: /faststorage/project/EcoGenetics/general_workflow_outputs/museomics
# collection sites and gps locations
#collection_sites_file: OBS
### OBS

# Make neutral VCF settings: (intergenic and rm repetitive)
#annotation_gtf: /home/anneaa/EcoGenetics/BACKUP/museomics/reference_genomes/Aglais_urticae/annotation/GCA_905147175.2_ilAglUrti1.2_genomic.gtf
# Bed file path
bed_files_path: /home/anneaa/EcoGenetics/BACKUP/museomics/reference_genomes/Gonepteryx_rhamni/annotation/
# VCF folders
#vcf_base_folder: /home/anneaa/EcoGenetics/general_workflow_outputs/museomics/vcf
# vcf tip folders
#vcf_base_folder: /home/anneaa/EcoGenetics/general_workflow_outputs/museomics/vcf/Gonepteryx_rhamni
# VCF filter settings? (threshold depth per pop or across pops, or across 70% of pops?)
# count of positions for calculating pi (only variants are called, thus we need a count of all sites, to calculate pi)
count_of_positions_file: /home/anneaa/EcoGenetics/general_workflow_outputs/museomics/vcf/Gonepteryx_rhamni/sitetable/GonRha.sitetable.tsv

# OBS: VCF files have been merged, so one vcf contains info from all pops (and only positions that are common)

vcf_file: /home/anneaa/EcoGenetics/general_workflow_outputs/museomics/vcf/Gonepteryx_rhamni/GonRha.freebayes_n3_p100_minaltfrc0_minaltcnt2_singlecall.merged.norm.bcftoolsfilter_AF0_SnpGap5_typesnps_biallelic_DP200-dynamic_AO1.vcf.gz
    

# List of populations to exclude:
exclude_list:
  - 