# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,vcf:workflowconfiguration
# The name of the relevant project account.
account: spider2
# Taxonomic group.
taxonomic_group: Collembola
# Name of species being analyzed.
species_name: Orchesella villosa
# Path to reference genome.
reference_genome_path: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Orchesella_villosa/EG_OrcVil_23072024_genomic.fna
# BED file indicating intergenic regions of reference genome.
intergenic_bed_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Orchesella_villosa/annotation/EG_OrcVil_23072024_genomic.intergenic.bed
# (str). BED file indicating repetitive regions of the reference genome.
repeats_bed_file: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Orchesella_villosa/annotation/EG_OrcVil_23072024_genomic.repeats.bed
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps/
# Directory for final output files. (If left empty, output file will be placed within 'working_directory_path').
output_directory_path: /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/
# Partition size of genome in base pairs.
partition_size: 100000
# Freebayes settings.
freebayes_settings:
  sample_ploidy: 100
  best_n_alleles: 3
  min_alternate_fraction: 0
  min_alternate_count: 2
  memory: 80
  time: '1-24:00:00'
# Filtering depths, limits included.
filtering:
  minimum_depth: 200
# Mode for creating VCF file (1 | 2 | 3 | 4).
# 1 = Separate VCF files for each sample/BAM file. 2 = One VCF file per sample group. 3 = One VCF containing data for all samples/BAM files. 4 = All.
mode: 1
# Batch settings. Can be used to reduced the number of jobs sent to the queue at one time.
# Only partial VCF files will be created when batching. To complete the full workflow one must do a no-batch run.
batch_settings:
  # (int). The number of batches to create. 0 = don't batch jobs. If left empty defaults to '0'
  number_of_batches: 
  # (int). Which of the created batches to run. Must be >=1 AND <=number_of_batches. Can be left empty if number_of_batches is '0'.
  current_batch_number: 
# Sample setup. List of dictionaries listing the configuration for each sample.
sample_list:
  - 
    # Name of sample group.
    group_name: Grassland
    # List of paths to BAM files.
    bam_file_list:
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/grassland/OrcVil_BRS-C95/OrcVil_BRS-C95.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/grassland/OrcVil_DSJ-C235/OrcVil_DSJ-C235.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/grassland/OrcVil_FaaJ-C5/OrcVil_FaaJ-C5.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/grassland/OrcVil_HAS-C58/OrcVil_HAS-C58.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/grassland/OrcVil_KOS-C292/OrcVil_KOS-C292.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/grassland/OrcVil_KRS-C187/OrcVil_KRS-C187.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/grassland/OrcVil_MSJ-C3/OrcVil_MSJ-C3.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/grassland/OrcVil_NYS-F-C26/OrcVil_NYS-F-C26.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/grassland/OrcVil_ORoe-C193/OrcVil_ORoe-C193.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/grassland/OrcVil_RES-C167/OrcVil_RES-C167.filtered.bam 
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/grassland/OrcVil_SKS-C54/OrcVil_SKS-C54.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/grassland/OrcVil_ULJ-C123/OrcVil_ULJ-C123.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/grassland/OrcVil_VIS-C359/OrcVil_VIS-C359.filtered.bam
  - 
    # Name of sample group.
    group_name: Conservation_agriculture
    # List of paths to BAM files.
    bam_file_list:
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/conservation_agriculture/OrcVil_CA-KNJ-C208/OrcVil_CA-KNJ-C208.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/conservation_agriculture/OrcVil_CA-MoeJ-C353/OrcVil_CA-MoeJ-C353.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/conservation_agriculture/OrcVil_CA-LES-C386/OrcVil_CA-LES-C386.filtered.bam
  - 
    # Name of sample group.
    group_name: Conventional_agriculture
    # List of paths to BAM files.
    bam_file_list:
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/conventional_agriculture/OrcVil_K-KNJ-C219/OrcVil_K-KNJ-C219.filtered.bam
  - 
    # Name of sample group.
    group_name: Outgroup_Orchesella_cincta
    # List of paths to BAM files.
    bam_file_list:
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/outgroup_orchesella_cincta/OrcCin_aeRoe-C182/OrcCin_aeRoe-C182.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/outgroup_orchesella_cincta/OrcCin_DSJ-C233/OrcCin_DSJ-C233.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/outgroup_orchesella_cincta/OrcCin_FaaJ-C6/OrcCin_FaaJ-C6.filtered.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/collembola/Orchesella_villosa/outgroup_orchesella_cincta/OrcCin_JHJ-C222/OrcCin_JHJ-C222.filtered.bam
