# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,mapping:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Taxonomic group
taxonomic_group: beetles
# Name of species being analyzed
species_name: Tachyporus hypnorum
# Path to reference genome file in FASTA format
reference_genome_path: 	
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps
# # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
output_directory_path: /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/
# AdapterRemoval settings.
adapterremoval_settings:
  min_quality: 25
  min_length: 20
  adaptersequence1: AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
  adaptersequence2: AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG
# Samtools filter settings.
filter_settings:
  flags_excluded: 3844
  flags_required: 
  min_mq: 20
# List of path to sample folders containing resequencing data.
sample_lists:
  -
    group_name: Grassland
    sample_folder_list:
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_ADJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_aeRoe
#      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_BIJ_49ind
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_BRS
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_DSJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_FUR
#      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_GSJ_40ind
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_HAS
#      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_HHJ_39ind
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_KRS
#      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_LEJ_36ind
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_MSJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_MYS
#      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_RDJ_39ind
#      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_SBJ_45ind
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_SKJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_STF
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_STJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_TRJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_ULJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_UTJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_VAJ
#      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_aaRJ_45ind
  -
    group_name: Conservation_agriculture
    sample_folder_list:
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TecHyp_CA-FLJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TecHyp_CA-FSJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TecHyp_CA-HVJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TecHyp_CA-LES
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TecHyp_CA-MoeJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_BIJ_49ind
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TacHyp_CA-STJ_37ind
  -
    group_name: Conventional_agriculture
    sample_folder_list:
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TecHyp_K-FLJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TecHyp_K-HVJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TecHyp_K-JES
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TecHyp_K-MoeJ
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/beetles/Tachyporus_hypnorum/TecHyp_K-YDJ
  -
    group_name: Outgroup_Isotomurus_maculatus
    sample_folder_list: