# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,museomics,mapping:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed
species_name: Lycaena virgaureae
# Path to reference genome file in FASTA format
reference_genome_path: /faststorage/project/EcoGenetics/BACKUP/museomics/reference_genomes/Lycaena_virgaureae/EG_LycVir_01052024_genomic_haplotype1.fna
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/museomics/steps
# # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
output_directory_path: /faststorage/project/EcoGenetics/general_workflow_outputs/museomics
# AdapterRemoval settings.
adapterremoval_settings:
  min_quality: 25
  min_length: 20
  adaptersequence1: AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
  adaptersequence2: AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG
# Samtools filter settings.
filter_settings:
  flags_excluded: 3844
  flags_required: 
  min_mq: 20
# List of path to sample folders containing resequencing data.
# Data type: contemporary | historic | paired-end | single-end ...
sample_lists:
  -
    time_period: 2022
    data_type: contemporary, paired-end
    populations:
      -
        population_name: Jutland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_01_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_02_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_03_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_04_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_05_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_06_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_07_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_08_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_09_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_10_J_2022
      -
        population_name: Zealand
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_11_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_12_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_13_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_14_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_15_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_16_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_17_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_18_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_19_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_20_S_2022
  -
    time_period: 1985
    data_type: historic, single-end
    populations:
      -
        population_name: Jutland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_21_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_22_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_23_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_24_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_25_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_26_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_27_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_28_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_29_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_30_J_1985
      -
        population_name: Zealand
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_31_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_32_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_33_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_34_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_35_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_36_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_37_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_38_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_39_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_40_S_1985
  -
    time_period: 1950
    data_type: historic, single-end
    populations:
      -
        population_name: Jutland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_41_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_42_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_43_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_44_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_45_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_46_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_47_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_48_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_49_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_50_J_1950
      -
        population_name: Zealand
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_51_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_52_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_53_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_54_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_55_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_56_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_57_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_58_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_59_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_60_S_1950
  -
    time_period: 1915
    data_type: historic, single-end
    populations:
      -
        population_name: Jutland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_61_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_62_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_63_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_64_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_65_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_66_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_67_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_68_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_69_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_70_J_1915
      -
        population_name: Zealand
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_71_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_72_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_73_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_74_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_75_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_76_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_77_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_78_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_79_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_80_S_1915
  -
    time_period: Pooled
    data_type: contemporary, paired-end
    populations:
      -
        population_name: Pooled_extraction
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/denmark/Lycaena_virgaureae/LyVi_poolseq_2022
  -
    time_period: 2023
    data_type: contemporary, paired-end
    populations:
      -
        population_name: Finland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/LV23_1
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/LV23_2
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/LV23_3
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/LV23_4
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/LV23_5
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/LV23_11
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/LV23_12
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/LV23_13
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/LV23_14
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/LV23_15
  -
    time_period: 1986
    data_type: historic, single-end
    populations:
      -
        population_name: Finland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M91
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M92
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M93
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M94
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M95
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M96
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M97
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M98
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M99
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M100
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M101
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M102
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M103
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M104
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M105
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M106
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M107
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M108
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M109
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M110
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M111
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M112
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M113
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M114
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M115
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M116
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M117
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M118
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M119
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M120
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M324
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M325
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M326
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M327
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M328
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M329
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M330
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M331
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M332
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M333
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M334
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M335
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M336
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M337
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M338
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M339
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M340
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M341
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M342
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M343
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M344
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M345
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M346
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M347
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M348
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M349
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M350
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M351
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M352
          - /faststorage/project/EcoGenetics/BACKUP/museomics/fastq/finland/Lycaena_virgaureae/Lvg_M353
