# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,mapping:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Taxonomic group
taxonomic_group: spiders
# Name of species being analyzed
species_name: Oedothorac fuscus
# Path to reference genome file in FASTA format
reference_genome_path: /faststorage/project/EcoGenetics/people/jilong/genome_asm_jeppe/steps/spiders/Oedothorax_fuscus/draft_assembly/purge_dups_hic/04/OedFus.purged.fa
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jesper_Bechsgaard/test
# # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
output_directory_path: /faststorage/project/EcoGenetics/people/Jesper_Bechsgaard/test/OedFus
# AdapterRemoval settings.
adapterremoval_settings:
  min_quality: 25
  min_length: 20
  adaptersequence1: AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
  adaptersequence2: AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG
# Samtools filter settings.
filter_settings:
  flags_excluded: 3844
  flags_required: 
  min_mq: 20
# List of path to sample folders containing resequencing data.
sample_lists:
  -
    group_name: Grassland
    sample_folder_list:
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/spiders/Oedothorac_fuscus/OedFus_BRS
  -
    group_name: Conservation_agriculture
    sample_folder_list:
  -
    group_name: Conventional_agriculture
    sample_folder_list:
  -
    group_name: Outgroup_
    sample_folder_list: