# Tag identifying file association.
TAG: jilong:EcoGenetics,site_frequency_spectrum_single_population:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed
species_name: Gonepteryx rhamni
# ID of species for short
species_id : GonRha
# Name of the task as a unique id:
task_id: split_ann_vcf
# Species genome annotation file, gff:
annotation_gff: /faststorage/project/EcoGenetics/BACKUP/museomics/reference_genomes/Gonepteryx_rhamni/annotation/EG_GonRha_22032024_genomic.gff
#species gene bed file
gene_bed: /faststorage/project/EcoGenetics/BACKUP/museomics/reference_genomes/Gonepteryx_rhamni/annotation/EG_GonRha_22032024_genomic.genes.bed
#species intergenic bed file
intergenic_bed: /faststorage/project/EcoGenetics/BACKUP/museomics/reference_genomes/Gonepteryx_rhamni/annotation/EG_GonRha_22032024_genomic.intergenic.bed
# Species genome fasta:
genome_fasta: /faststorage/project/EcoGenetics/BACKUP/museomics/reference_genomes/Gonepteryx_rhamni/EG_GonRha_22032024_genomic.fna
# Population to retrive:
population: GoRh_pool50
# snpEff annotated vcf file:
ann_vcf: /faststorage/project/EcoGenetics/people/jilong/sfs/steps/GonRha/GoRh_poolseq_2022/GoRh_poolseq_2022_ann.vcf
# raw vcf file, freebayes called:
raw_vcf: /faststorage/project/EcoGenetics/general_workflow_outputs/museomics/vcf/Gonepteryx_rhamni/GonRha.freebayes_n3_p100_minaltfrc0_minaltcnt2_singlecall.merged.norm.vcf.gz
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/general_workflow_outputs/sfs/single_pop_sfs/GonRha
#Directory for final output files
output_directory_path: /faststorage/project/EcoGenetics/general_workflow_outputs/sfs/single_pop_sfs/GonRha
# Directory for log files
log_directory_path: /faststorage/project/EcoGenetics/general_workflow_outputs/sfs/single_pop_sfs/GonRha/logs
# Directory for helping functions and scripts
help_scripts_path: /faststorage/project/EcoGenetics/general_workflows/population_genetics/sfs/workflow_sources
# Directory for input data files
data_directory_path: /faststorage/project/EcoGenetics/people/jilong/sfs/data/GonRha
# BAM alignment file of the populaiton
population_bam_alignment: /faststorage/project/EcoGenetics/general_workflow_outputs/museomics/alignments/Gonepteryx_rhamni/Pooled/pooled_extraction/GoRh_pool50/GoRh_pool50.filtered.bam
# Depth summary of the freebayes called variants for the population
population_varaint_depth_summary: /faststorage/project/EcoGenetics/general_workflow_outputs/museomics/vcf/Gonepteryx_rhamni/depth_distribution/GonRha.depth.tsv  
