# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,filter,aa,snpeff:workflowconfiguration
# (str). The name of the relevant project account.
account: EcoGenetics
# (str). Name of species being analyzed
speciesName: Isotoma viridis
# (str). Taxonomic group. Can be left empty.
taxonomicGroup: Collembola
# (str). Directory for intermediary files.
workingDirectoryPath: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps
# (str). Directory for final output files.
outputDirectoryPath: /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics
# (str). Path to reference genome file.
referenceGenome: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Isotoma_viridis/EG_IsoVir_23082024_genomic.fna
# (str). Path to reference genome annotation file in GTF format. Can be left empty. If left empty VCF file will not be SnpEff or AA annotated.
gtfAnnotation: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Isotoma_viridis/annotation/EG_IsoVir_23082024_genomic.gtf
# (dict). Settings for outgroup data. Can be left empty. If left empty VCF file will not be AA annotated.
outgroupSettings:
  # (str). Path to outgroup VCF file. This file should NOT be filtered.
  vcfFile:
  # (str). Path to BED file containing intervals for which the outgroup has coverage ranging within threshold values. 
  withinThresholdBedFile: 
# (str). Path BED file containing intergenic regions.
intergenicBedFile: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Isotoma_viridis/annotation/EG_IsoVir_23082024_genomic.intergenic.bed
# (str). Path to BED file containing repeat regions.
repeatsBedFile: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Isotoma_viridis/annotation/EG_IsoVir_23082024_genomic.repeats.bed
# (list). Setup for VCF files to be filtered and annotated.
vcfGroupList:
  -
    # (str). Name of sample group.
    groupName: Grassland
    # (str). Path to VCF file.
    vcfFile: /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/vcf/collembola/Isotoma_viridis/grassland/IsoVir.grassland.ingroup.allQuality.freebayes.merge.vcf.gz
    # (int). Minimum coverage value for filtering.
    minimumCoverage: 200
    # (int). Maximum coverage value for filtering.
    maximumCoverage: 668
    # (str). Path to BED file containing intervals for which the sample group has coverage ranging within threshold values. 
    withinThresholdBedFile: /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/vcf/collembola/Isotoma_viridis/depth/IsoVir.grassland.ingroup.allQuality.depththreshold.bed
  -
    # (str). Name of sample group.
    groupName: Conventional agriculture
    # (str). Path to VCF file.
    vcfFile: /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/vcf/collembola/Isotoma_viridis/conventional_agriculture/IsoVir.conventional_agriculture.ingroup.allQuality.freebayes.merge.vcf.gz
    # (int). Minimum coverage value for filtering.
    minimumCoverage: 200
    # (int). Maximum coverage value for filtering.
    maximumCoverage: 716
    # (str). Path to BED file containing intervals for which the sample group has coverage ranging within threshold values. 
    withinThresholdBedFile: /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/vcf/collembola/Isotoma_viridis/depth/IsoVir.conventional_agriculture.ingroup.allQuality.depththreshold.bed
  -
    # (str). Name of sample group.
    groupName: Conservation agriculture
    # (str). Path to VCF file.
    vcfFile: /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/vcf/collembola/Isotoma_viridis/conservation_agriculture/IsoVir.conservation_agriculture.ingroup.allQuality.freebayes.merge.vcf.gz
    # (int). Minimum coverage value for filtering.
    minimumCoverage: 200
    # (int). Maximum coverage value for filtering.
    maximumCoverage: 568
    # (str). Path to BED file containing intervals for which the sample group has coverage ranging within threshold values. 
    withinThresholdBedFile: /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/vcf/collembola/Isotoma_viridis/depth/IsoVir.conservation_agriculture.ingroup.allQuality.depththreshold.bed